local radarTextureNames = {
    "arrow",
    "radardisc",
    "radarRingPlane",
    "radar_airYard",
    "radar_ammugun",
    "radar_barbers",
    "radar_BIGSMOKE",
    "radar_boatyard",
    "radar_bulldozer",
    "radar_burgerShot",
    "radar_cash",
    "radar_CATALINAPINK",
    "radar_centre",
    "radar_CESARVIAPANDO",
    "radar_chicken",
    "radar_CJ",
    "radar_CRASH1",
    "radar_dateDisco",
    "radar_dateDrink",
    "radar_dateFood",
    "radar_diner",
    "radar_emmetGun",
    "radar_enemyAttack",
    "radar_fire",
    "radar_Flag",
    "radar_gangB",
    "radar_gangG",
    "radar_gangN",
    "radar_gangP",
    "radar_gangY",
    "radar_girlfriend",
    "radar_gym",
    "radar_hostpital",
    "radar_impound",
    "radar_light",
    "radar_LocoSyndicate",
    "radar_MADDOG",
    "radar_mafiaCasino",
    "radar_MCSTRAP",
    "radar_modGarage",
    "radar_north",
    "radar_OGLOC",
    "radar_pizza",
    "radar_police",
    "radar_propertyG",
    "radar_propertyR",
    "radar_qmark",
    "radar_race",
    "radar_runway",
    "radar_RYDER",
    "radar_saveGame",
    "radar_school",
    "radar_spray",
    "radar_SWEET",
    "radar_tattoo",
    "radar_THETRUTH",
    "radar_TORENO",
    "radar_TorenoRanch",
    "radar_triads",
    "radar_triadsCasino",
    "radar_truck",
    "radar_tshirt",
    "radar_waypoint",
    "radar_WOOZIE",
    "radar_ZERO",
}

function replaceRadarTextures()

    for i, textureName in ipairs(radarTextureNames) do
		local textureReplaceShader = dxCreateShader("client/shaders/texture_replace.fx", 0, 0, false, "world")
    	local texture = dxCreateTexture("client/img/" .. textureName .. ".png")
    	dxSetShaderValue(textureReplaceShader, "gTexture", texture)
    	engineApplyShaderToWorldTexture(textureReplaceShader, textureName)
    end
end

addEventHandler("onClientResourceStart", resourceRoot, replaceRadarTextures)